### ISSUE TITLE
Better GPS antenna

### ISSUE THREAD

**Issue by matteocarnelos** [metis-vela-unipd/sailtrack-radio#4]
Without cable

**Comment by matteocarnelos** [comment]
Possible antenna: https://www.amazon.it/dp/B07CRX7GXN/?coliid=I1H8VHFPVA3YQY&colid=1AX6SKCA342FA&ref_=lv_ov_lig_dp_it&th=1

**Comment by Pidgey27** [comment]
L'antenna attuale é approssimativamente di 3 x 4 x 1,5 cm

**Comment by matteocarnelos** [comment]
Done
